language: scala

jdk:
  - oraclejdk8

scala:
   - 2.12.2

sudo: required
dist: precise
#
#script:
#  - sbt clean compile test

jobs:
  include:
    - stage: clean
      script: sbt clean
    - stage: compile
      script: sbt compile
    - stage: test
      script: sbt test